Больше деталей
htmlacademy-javascript/1543425-kekstagram-22 pull request #4
Opened 2021-02-25 10:34 UTC by daru365

2021-02-25 11:05 UTC, polina-prokofieva requested changes
1. Похоже, ты забыла обновить ветку master перед тем, как создать новую ветку. Из-за этого возникли конфликты. Не приятно, но это хорошая возможность научится их решать. Это можно сделать на сайте гитхаба или в терминале. Если не получится разобраться - помогу )
2. Хорошо бы проверять работоспособность кода перед тем, как сдевать задание, чтобы мы не тратили на это лишние проверки. Есть есть вопросы, то тоже можно обсудить заранее. В этом задании, чтобы проверить, что код работает, можно вывести сгенерированный массив объектов в консоль. Сам вывод в консоль можно убрать перед сдачей задания, но его можно и нужно использовать в процессе написания заданий, для проверки, что код работает правильно.
Сейчас код не работает. Ниже я оставлю несколько замечаний под конкретными строчками, но по сути тут не хватает части функциональности.

2021-02-25 11:14 UTC, polina-prokofieva requested changes

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +const likes = console.log(getRandomIntInclusive(15, 200));
Чему в итоге равны эти переменные? Что возвращает функция console.log?

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +const messages = [
Константы должны быть названы заглавными буквами [Б7](https://up.htmlacademy.ru/javascript/22/criteries#b7)

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +	message: messages[_.random(0, messages.length - 1)]
Тут не хватает запятой в конце. Этот код не работает и выбрасывает ошибку в консоль.

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +	idObject: getRandomIntInclusive(),
Что возвращает эта функция, вызванная без параметров?

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +	avatar: 'img/avatar-' + getRandomIntInclusive(1, 6) + '.svg',
Вот тут строка сгенерирована отлично! Я бы рекомендовала использовать шаблонные строки, но это только рекомендация, можно оставить, как есть.

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +	name: names[_.random(0, names.length - 1)],
Почему ты решила использовать функцию _.random, вместо своей функции getRandomIntInclusive?
В принципе, это допускается, можно не менять. Но хорошо бы на основе этой или своей аналогичной функции, написать функцию выдачи случайного элемента массива и использовать её в этих двух строках.

2021-02-25 11:14 UTC, polina-prokofieva commented on js/main.js
> +};
Нет функции, которая создаёт объект со случайными данными и функции, которая создаёт массив таких объектов.

2021-02-25 15:31 UTC, daru365 commented on js/main.js
> +    url: 'photos/' + getRandomIntInclusive(1, 25) + '.jpg',
Записала всё-таки через +, а не через $ - у меня в консоли не выводилось рандомное число при записи через $

2021-02-25 15:32 UTC, daru365 commented on js/main.js
> +generateArray();
Убрала console.log - линтер выдавал ошибку из-за консоли

2021-02-26 08:36 UTC, polina-prokofieva approved these changes

2021-02-26 08:36 UTC, polina-prokofieva commented on js/main.js
> +    url: 'photos/' + getRandomIntInclusive(1, 25) + '.jpg',
А не рандомное выводится? Думаю, проблема не в функции. Но пусть будет пока так.

2021-02-26 08:36 UTC, polina-prokofieva commented on js/main.js
> +generateArray();
Всё правильно, console.log - это только, чтобы проверить локально, что всё работает, в пулреквесте его быть не должно.

2021-02-26 08:36 UTC, merged